title: SE Conference Deadlines # (Maintained by @tdegueul)
description: This list is heavily biased towards my research topics.<br>I shall not be held liable for any missed deadline due to inaccuracies on this website ;)
author: Manuel Leduc

domain: "https://manuelleduc.github.io/se-deadlines/"
baseurl: /se-deadlines

twitter_username: manuel_leduc
#twitter_hashtag: machinelearning
github_username: manuelleduc
github_repo: se-deadlines

markdown: kramdown
#ga_id: UA-36274081-2
