title: SE Conference Deadlines # (Maintained by @tdegueul)
description: Countdowns to some SE conference/workshops deadlines
author: Thomas Degueule

#domain: "aideadlin.es"
baseurl: "/se-deadlines"

twitter_username: tdegueul
#twitter_hashtag: machinelearning
github_username: tdegueul
github_repo: se-deadlines

markdown: kramdown
#ga_id: UA-36274081-2
